### ISSUE TITLE
Thunderbird 60+

### ISSUE THREAD

**Issue by paulmoons** [xzer/sendfilter#2]
I know it's a long shot, but if someone is still developing this, it would be much appreciated to see an update for Thunderbird 60+

Thanks!

**Comment by davidegiannella** [comment]
+1!

**Comment by davidegiannella** [comment]
was browsing the codebase. Never did a TB plugin. However it looks like, if we're lucky we simply have to update the rdf and zip the whole `sendfilter` dir as`xpi`.  It will be a different discussion if we'll have changes along the way. I may be able to work on this if it's a simple fix. However looking at my schedule is quite hard.

**Comment by xzer** [comment]
AFAK, TB has been supporting outgoing filter from several years ago, which is why I stopped development.

**Comment by davidegiannella** [comment]
Indeed. I have the sendfilter disabled by still having the option for applying filters on the outgoing. I think we can close this one.

<img width="263" alt="screen shot 2019-01-04 at 10 50 08" src="https://user-images.githubusercontent.com/662081/50682283-a5dfb980-100e-11e9-9b9e-975df2e69b0e.png">
<img width="293" alt="screen shot 2019-01-04 at 10 50 30" src="https://user-images.githubusercontent.com/662081/50682284-a6785000-100e-11e9-98e6-07d6acffad7b.png">

**Comment by paulmoons** [comment]
@davidegiannella You're absolutely right. Great pick-up. Thanks for sharing!
